# 中等规模问题配置
# 标准测试场景

environment:
  num_trucks: 3
  num_drones: 3
  num_depots: 1
  num_customers: 15
  
  WT_max: 1000.0
  WD_max: 80.0
  max_charge: 50
  
  horizon: 200
  area_size: 15.0
  road_damage_ratio: 0.3

training:
  num_episodes: 2000
  max_episode_len: 1000
  batch_size: 256
  min_buffer_size: 5000
  warmup_steps: 3000

logging:
  exp_name: medium_problem

