# MADDPG算法特定配置
# Multi-Agent Deep Deterministic Policy Gradient

algorithm:
  name: maddpg
  type: off_policy

training:
  lr_actor: 1.0e-4
  lr_critic: 3.0e-4
  gamma: 0.95
  tau: 0.01
  
  batch_size: 256
  update_freq: 10
  target_update_freq: 100
  min_buffer_size: 5000
  
  # 探索参数
  warmup_steps: 3000
  epsilon_max: 1.0
  epsilon_min: 0.1
  epsilon_decay_steps: 30000

network:
  actor:
    hidden_units: [512, 256]
    activation: relu
  critic:
    hidden_units: [1024, 512, 256]
    activation: relu

features:
  use_per: false
  use_iam: true

